### ISSUE TITLE
NullPointerException in AMIGetpapersTool

### ISSUE THREAD

**Issue by richardofsussex** [petermr/openVirus#43]
Trying a 'Hello World!' test of getpapers, on a Linux Mint laptop from the command line.  Just trying to run the query found in the documentation:

richard@richard-SATELLITE-Z830:~/ami3/target/appassembler/bin/test1$ ../ami getpapers -q "((social distance) AND (epidemic))" 

Generic values (AMIGetpapersTool)
================================
-v to see generic values

Specific values (AMIGetpapersTool)
================================

java.lang.NullPointerException
	at org.contentmine.ami.tools.AMIGetpapersTool.runGetpapers(AMIGetpapersTool.java:88)
	at org.contentmine.ami.tools.AMIGetpapersTool.runSpecifics(AMIGetpapersTool.java:79)
	at org.contentmine.ami.tools.AbstractAMITool.runCommands(AbstractAMITool.java:203)
	at org.contentmine.ami.tools.AbstractAMITool.call(AbstractAMITool.java:183)
	at org.contentmine.ami.tools.AbstractAMITool.call(AbstractAMITool.java:33)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at org.contentmine.ami.tools.AMI.main(AMI.java:102)

**Comment by richardofsussex** [comment]
This error is caused by trying to use getpapers from within the AMI code.  It needs to be downloaded as a separate resource.  See the FAQ: https://github.com/petermr/openVirus/wiki/FAQ
