### ISSUE TITLE
SPARQL2ami : needed amidict syntax for dictionary creation

### ISSUE THREAD

**Issue by vaishaliarora277** [petermr/openVirus#77]
I am trying to convert the dictionary funder created by SPARQL into amidict format. To do this, I first converted the XML file created by SPARQL into .txt and used it as input file while running the command :

`amidict -v --dictionary funder --directory mydictionaries --input funder.txt create --informat list --outformats xml,html --wikilinks wikipedia, wikidata
 `

The output to the command came as:

```
....
N 26988; T 26988
![Fatal Error] :192:5: The element type "input" must be terminated by the matching end-tag "</input>".
<192/5>badline >                </div>
                </div>
Cannot add entry: nu.xom.ParsingException: The element type "input" must be terminated by the matching end-tag "</input>". at line 192, column 5
![Fatal Error] :192:5: The element type "input" must be terminated by the matching end-tag "</input>".
<192/5>badline >                </div>
                </div>
....
```

**Comment by vaishaliarora277** [comment]
Few lines from the file 'funder_file.txt' 

```
...
<?xml version='1.0' encoding='UTF-8'?>
<sparql xmlns='http://www.w3.org/2005/sparql-results#'>
	<head>
		<variable name='item'/>
		<variable name='Crossref_funder_ID'/>
	</head>
	<results>
		<result>
			<binding name='item'>
				<uri>http://www.wikidata.org/entity/Q771</uri>
			</binding>
			<binding name='Crossref_funder_ID'>
				<literal>100006637</literal>
			</binding>
		</result>
...
```

**Comment by Priya-Jk-15** [comment]
I am Windows 10 user. I am trying to create `disease` dictionary from ICD-10 using SPARQL. I downloaded the results from SPARQL as an xml file named `diseasealt` and gave the syntax `amidict -v --dictionary disease --directory dic --input diseasealt create --informat wikisparqlxml`. I also changed and tried the syntax `amidict -vvv --dictionary disease_icd --directory dic --input diseasealt.xml create --informat wikisparqlxml`.

I was not able to create the dictionary and got the same following output for both the above syntax:
```
.
.
Specific values (DictionaryCreationTool)
==================
names [DiseaseLabel, instanceofLabel, DiseaseAltLabel, Disease, ICDcode]
java.lang.NullPointerException
            at org.contentmine.ami.tools.dictionary.DictionaryCreationTool.addWikidataID(DictionaryCreationTool.java:594)
            org.contentmine.ami.tools.dictionary.DictionaryCreationTool.readSparqlXml(DictionaryCreationTool.java.447)
            org.contentmine.ami.tools.dictionary.DictionaryCreationTool.createDictionary(DictionaryCreationTool.java:304)
            org.contentmine.ami.tools.dictionary.DictionaryCreationTool.runSub(DictionaryCreationTool.java:224)
            org.contentmine.ami.tools.AbstractAMIDictTool.runSpecifies(AbstractAMIDictTool.java:423)
            org.contentmine.ami.tools.AbstractAMIDictTool.runCommands(AbstractAMIDictTool.java:93)
            org.contentmine.ami.tools.AbstractAMIDictTool.call(AbstractAMIDictTool.java:74)
            org.contentmine.ami.tools.AbstractAMIDictTool.call(AbstractAMIDictTool.java:55)
            at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
            at picocli.CommandLine.access$1100(CommandLine.java:145)
            at picocli.CommandLine$RunLast.executableUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
            at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
            at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
            at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
            at org.contentmine.ami.tools.AMIDict.enhancedLoggingExecutionStrategy(AMIDict.java:144)
            at picocli.CommandLine.execute(CommandLine.java:2058)
            at org.contentmine.ami.tools.AMIDict.main(AMIDict.java:83)
```
The log file of the second syntax is [ami.log](https://github.com/petermr/openVirus/files/4967105/ami.log). @petermr Kindly guide  me with the syntax.

**Comment by petermr** [comment]
OK,
Thanks
The problem is that the names from the SPARQL query need to be the same as in the dictionary, e.g. "term", "wikidataID". I think we should have a map so the user has to make the mapping. I will make this mandatory. I'll try to mend this tonight.

**Comment by Priya-Jk-15** [comment]
To create `dictionary` from `SPARQL` using `amidict` syntax, refer https://github.com/petermr/ami3/wiki/amidict:-wikisparql
